# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jlrei/Documents/SourceTree/EE324_Lab6/EE324_Lab6.srcs/sources_1/bd/System/ip/System_clk_wiz_0_1/System_clk_wiz_0_1.xci
# IP: The module: 'System_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jlrei/Documents/SourceTree/EE324_Lab6/EE324_Lab6.srcs/sources_1/bd/System/ip/System_clk_wiz_0_1/System_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlrei/Documents/SourceTree/EE324_Lab6/EE324_Lab6.srcs/sources_1/bd/System/ip/System_clk_wiz_0_1/System_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlrei/Documents/SourceTree/EE324_Lab6/EE324_Lab6.srcs/sources_1/bd/System/ip/System_clk_wiz_0_1/System_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/jlrei/Documents/SourceTree/EE324_Lab6/EE324_Lab6.srcs/sources_1/bd/System/ip/System_clk_wiz_0_1/System_clk_wiz_0_1.xci
# IP: The module: 'System_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jlrei/Documents/SourceTree/EE324_Lab6/EE324_Lab6.srcs/sources_1/bd/System/ip/System_clk_wiz_0_1/System_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlrei/Documents/SourceTree/EE324_Lab6/EE324_Lab6.srcs/sources_1/bd/System/ip/System_clk_wiz_0_1/System_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlrei/Documents/SourceTree/EE324_Lab6/EE324_Lab6.srcs/sources_1/bd/System/ip/System_clk_wiz_0_1/System_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
